experiment:
    id: fasterrcnn
    seed: 1234

checkpoint: 'checkpoints'
tensorboard: 'runs'

##Data
data:
    train: '/root/PhenoBench/train'
    val: '/root/PhenoBench/val'
    
##Training
train:
    n_gpus: 1  # Set to 0 since we're using CPU
    workers: 8
    max_epoch: 100
    batch_size: 12
    n_classes: 3
    overfit: False
    lr: 0.0001

val:
    nms_th: 0.5
    prob_th: 0.6
